backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/images/blog" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/images/blog"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

    
  - name: 'about' # Collection name (you can customize this)
    label: 'About Page' # Display label in CMS
    folder: 'src' # Path to your Markdown files
    create: true
    slug: '{{slug}}' # Optional: Customize the URL slug
    fields:
      - { label: 'Description', name: 'description', widget: 'string' } # Example field
      - { label: "Featured Image", name: "image", widget: "image" }   

  - name: 'cat' # Collection name (you can customize this)
    label: 'Cat' # Display label in CMS
    folder: '_data/cat' # Path to your Markdown files
    create: true
    slug: '{{slug}}' # Optional: Customize the URL slug
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Categories", name: "cat", widget: "list", allow_add: true, allow_delete: true } # Example field
     
